/** @exports Sidebar */
//module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 /// myAutogeneratedSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
//};
const generateSidebar = require('./generateSidebar.js')

const docs = generateSidebar({ baseDir:'./docs', sourceDir: '', ignoreDirectories: '.idea,.git' })

module.exports = {
  docs: docs,
}